# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptoroot";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptoroot".device = "/dev/disk/by-uuid/f60741d0-8120-421a-b598-f35d5072b141";


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51c4-3291";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Нужно добавить:
  fileSystems."/home" = {
    device = "/dev/mapper/cryptoroot";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
